{% set version = "0.0.11" %}
{% set python_min = "3.10" %}

package:
  name: tmux-language-server
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tmux-language-server/tmux_language_server-{{ version }}.tar.gz
  sha256: 2ba7bb9aa1ab873fea5edc37af36748cca28329d34de95cc6afb1f4fde25829b

build:
  entry_points:
    - tmux-language-server = tmux_language_server.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - setuptools-generate >=0.0.6
    - pip
  run:
    - python >={{ python_min }}
    - lsp-tree-sitter
    - tree-sitter-tmux

test:
  imports:
    - tmux_language_server
  commands:
    - pip check
    - tmux-language-server --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/Freed-Wu/tmux-language-server
  summary: tmux language server
  dev_url: https://github.com/Freed-Wu/tmux-language-server
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
