schema_version: 1

context:
  version: "0.1.2"

package:
  name: tmux-language-server
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/tmux-language-server/tmux_language_server-${{ version }}.tar.gz
  sha256: 333b69c75be1e7efd27c77e3e7e018d03f0dc102d21857009bb6b0e6be52e803

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - tmux-language-server = tmux_language_server.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm >=6.2
    - setuptools-generate >=0.0.6
    - pip
    - uv-build
  run:
    - python >=${{ python_min }}
    - lsp-tree-sitter >=0.2.13
    - tree-sitter-tmux

tests:
  - python:
      imports:
        - tmux_language_server
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - tmux-language-server --help

about:
  summary: tmux language server
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/Freed-Wu/tmux-language-server
  repository: https://github.com/Freed-Wu/tmux-language-server

extra:
  recipe-maintainers:
    - danielnachun
